<?php

/**
 * @file ting_covers.module
 * Provide functionality and page callbacks for retrieving covers for Ting objects and collections
 */

define('TING_COVERS_DEFAULT_CACHE_LIFETIME', 86400);
define('TING_COVERS_MAX_SIZE', 1200);

// Load field module hooks.
module_load_include('inc', 'ting_covers', 'ting_covers.field');

/**
 * Implementation of hook_menu().
 */
function ting_covers_menu() {
  $items = array();

  $items['ting/covers'] = array(
    'title' => 'Retreives cover for Ting objects',
    'page callback' => 'ting_covers_objects',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'ting_covers.pages.inc',
  );

  $items['admin/config/ting/covers'] = array(
    'title' => 'Covers',
    'description' => 'Configure how covers are handled.',
  	'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_covers_admin_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ting_covers.admin.inc',
  );

  $items['admin/config/ting/covers/setttings'] = array(
    'title' => 'Settings',
    'description' => 'Configure how covers are handled.',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['admin/config/ting/covers/addi'] = array(
    'title' => 'ADDI service',
    'description' => 'Configure integration with the ADDI service.',
  	'page callback' => 'drupal_get_form',
    'page arguments' => array('ting_covers_admin_addi_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ting_covers.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implementation of hook_theme().
 */
function ting_covers_theme() {
  return array(
    'ting_object_cover' => array(
      'render element' => 'elements',
      'file' => 'ting_covers.theme.inc',
    ),
  );
}

/**
 * Implementation of hook_cron().
 */
function ting_covers_cron() {
  _ting_covers_delete_old_files($_SERVER['REQUEST_TIME'] - variable_get('ting_covers_cache_lifetime', TING_COVERS_DEFAULT_CACHE_LIFETIME));
}

/**
 * Implementation of hook_cache_clear().
 */
function ting_covers_flush_caches() {
  _ting_covers_delete_old_files($_SERVER['REQUEST_TIME'] - variable_get('ting_covers_cache_lifetime', TING_COVERS_DEFAULT_CACHE_LIFETIME));
}

/**
 * Implements hook_ding_install_tasks().
 */
function ting_covers_ding_install_tasks() {
  module_load_include('inc', 'ting_covers', 'ting_covers.admin');
  return array(
    'ting_covers_admin_addi_settings_form' => array(
      'display_name' => st('ADDI service settings'),
      'type' => 'form',
      'file' => drupal_get_path('module', 'ting_covers') . '/ting_covers.admin.inc',
    ),
  );
}

/**
 * Template preprocessor.
 */
function ting_covers_preprocess_ting_object(&$variables) {
  /*
   * Add the image style as a class, allowing templates to react on the size.
   */
  if (isset($variables['elements']['ting_cover'][0])) {
    $variables['classes_array'][] = drupal_html_class('imagestyle-' . $variables['elements']['ting_cover'][0]['#image_style']);
  }
}

/**
 * Delete ting covers files.
 *
 * @todo: handle image styles better and use API to flush expired images.
 *
 * @param int $time Timestamp where older files will be deleted.
 * 	Omit or set to NULL to delete all files.
 */
function _ting_covers_delete_old_files($time = NULL) {
  // Collect potential locations of cover folders
  $files_dir = file_default_scheme() . '://';
  $image_dirs = array($files_dir);

  $styles_dir = $files_dir . 'styles';
  foreach (scandir($styles_dir) as $style_dir) {
    $style_dir = $styles_dir . DIRECTORY_SEPARATOR . $style_dir . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR;
    if (is_dir($style_dir)) {
      $image_dirs[] = $style_dir;
    }
  }

  // Collect cover files
  $cover_files = array();
  foreach ($image_dirs as $uri) {
    $ting_covers_dir = $uri . 'ting' . DIRECTORY_SEPARATOR . 'covers';
    if (is_dir($ting_covers_dir)) {
      $cover_files = array_merge($cover_files, file_scan_directory($ting_covers_dir, "/./"));
    }
  }

  //Delete obsolete files
  foreach ($cover_files as $file) {
    if (!$time || (filemtime($file->uri) < $time)) {
      file_unmanaged_delete($file->uri);
    }
  }
}

/**
 * Return the path to the cover of the object.
 */
function ting_covers_object_path($object_id) {
  return file_default_scheme() . '://ting' . DIRECTORY_SEPARATOR . 'covers' . DIRECTORY_SEPARATOR . 'object' . DIRECTORY_SEPARATOR . md5($object_id) . '.jpg';
}
/**
 * Get covers for an array of ids.
 *
 * @param array $requested_covers
 *   Ids of entities to return covers for.
 *
 * @return array
 *   Array of id => file path for found covers.
 */
function ting_covers_get(array $requested_covers) {
  $entities = array();
  $covers = array();

  // Create array of loaded entities for passing to hooks.
  foreach ($requested_covers as $id) {
    // Ensure that the id at least seems valid.
    if (!mb_check_encoding($id, "UTF-8")) {
      continue;
    }

    // Determine if the local id is a known negative.
    if (cache_get('ting_covers:' . $id, FALSE)) {
      continue;
    }

    // If we we already have a valid cover image, use it.
    $path = ting_covers_object_path($id);
    if (file_exists($path)) {
      $covers[$id] = $path;
      continue;
    }

    // Queue for fetching by hook.
    $entities[$id] = ding_entity_load($id);
  }

  // Fetch covers by calling hook.
  
    foreach (module_invoke('ting_covers', 'ting_covers', $entities) as $id => $uri) {
      if ($uri && $path = _ting_covers_get_file($id, $uri)) {
        $covers[$id] = $path;
      }
      // Remove elements where a cover has been found, or suppressed.
      unset($entities[$id]);
    }
  

  // Mark all remaining as not found in cache.
  foreach ($entities as $id => $entity) {
    cache_set('ting_covers:' . $id, 1, 'cache', $_SERVER['REQUEST_TIME'] + TING_COVERS_DEFAULT_CACHE_LIFETIME);
  }

  return $covers;
}

/**
 * Moves/downloads an URI into the cover cache.
 *
 * @param string $id
 *   Ting entity id.
 * @param string $uri
 *   URI of file or local path.
 */
function _ting_covers_get_file($id, $uri) {
  if (!($url = parse_url($uri))) {
    // Seriously malformed, ignore it.
    return FALSE;
  }

  // Flat paths don't get a scheme.
  if (!isset($url['scheme']) && file_exists($uri)) {
    $url['scheme'] = 'file';
  }

  $path = ting_covers_object_path($id);

  switch ($url['scheme']) {
    case 'http':
    case 'https':
      if (ting_covers_fetch_image($path, $uri)) {
        return $path;
      }
      break;

    case 'public':
    case 'private':
    case 'file':
      if (file_unmanaged_copy($uri, $path)) {
        return $path;
      }
  }

  return FALSE;
}
/**
 * Implements hook_ting_covers().
 *
 * Fetch covers from AdditionalInformation service.
 */
function ting_covers_ting_covers($entities) {
  $covers = array();

  // Exceptions should only be thrown if something is so wrong,
  // that no images can be fetched whatsoever.
  try {
    $service = new AdditionalInformationService(variable_get('addi_wsdl_url'), variable_get('addi_username'), variable_get('addi_group'), variable_get('addi_password'));

    // Retrieve covers by PID.
    $retrieved = $service->getByPid(array_keys($entities));

    foreach ($retrieved as $pid=> $cover) {
      // Try to extract the image url from the result.
      $source_url = FALSE;
      if ($cover->detailUrl) {
        $source_url = $cover->detailUrl;
      }
      elseif ($cover->thumbnailUrl) {
        $source_url = $cover->thumbnailUrl;
      }

      if ($source_url) {
        // Return the path to the cover.
        $covers[$pid] = $source_url;
      }
    }
  }
  catch (Exception $e) {
    watchdog('ting_covers_addi', 'Unable to retrieve covers from ADDI: %message', array('%message' => $e->getMessage()), WATCHDOG_ERROR);

    // Error in fetching, return no covers.
    return array();
  }

  // Return all image information.
  return $covers;
}
/**
 * Helper function to fetch and save a cover image file.
 *
 * Cover fetching modules should use this if fetching the cover is a simple GET
 * request.
 *
 * @param string $filename
 *   File name, including its path within Drupal's file folder.
 * @param string $image_url
 *   URL for the source image file.
 *
 * @return mixed
 *   A string with the path of the image or FALSE on error.
 *
 * @see image_style_create_derivative()
 */
function ting_covers_fetch_image($filename, $image_url) {
  $result = drupal_http_request($image_url);

  // Bail if the HTTP request failed.
  if ($result->code != 200) {
    return FALSE;
  }

  // Get the folder for the final location of this preset.
  $directory = dirname($filename);

  // Build the destination folder tree if it doesn't already exist.
  if (!file_prepare_directory($directory, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS)) {
    watchdog('ting_covers', 'Failed to create directory: %directory', array('%directory' => $directory), WATCHDOG_ERROR);
    return FALSE;
  }

  $file = file_unmanaged_save_data($result->data, $filename, FILE_EXISTS_REPLACE);

  if ($file) {
    $realpath = drupal_realpath($filename);
    // Check that the file is an image. If not we'll remove again and return
    // FALSE to avoid broken images in frontend.
    if (!$size = getimagesize($realpath)) {
      file_unmanaged_delete($file);
      watchdog('ting_covers', 'Discarded invalid cover file from %url', array('%url' => $image_url), WATCHDOG_ERROR);
      return FALSE;
    }

    // Sometimes we get images in print quality, which makes imagecache run out
    // of memory in the attempt to resize it. So we check the image size and
    // scale it down to a more manageable size using the Imagemagick shell
    // command which gets around the memory limit.
    if ($size[0] > TING_COVERS_MAX_SIZE || $size[1] > TING_COVERS_MAX_SIZE) {
      exec('convert ' . $realpath . ' -resize ' . TING_COVERS_MAX_SIZE . 'x ' .
           $realpath . '.tmp', $output, $rc);
      // If successful, replace original image with scaled version.
      if ($rc == 0) {
        rename($realpath . '.tmp', $realpath);
      }
    }

    return $file;
  }

  return FALSE;
}